/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyworkspacesIndexRouteImport } from './routes/myworkspaces.index'
import { Route as MyworkspacesWorkspaceIdRouteImport } from './routes/myworkspaces.$workspaceId'
import { Route as MyworkspacesWorkspaceIdIndexRouteImport } from './routes/myworkspaces.$workspaceId.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyworkspacesIndexRoute = MyworkspacesIndexRouteImport.update({
  id: '/myworkspaces/',
  path: '/myworkspaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyworkspacesWorkspaceIdRoute = MyworkspacesWorkspaceIdRouteImport.update({
  id: '/myworkspaces/$workspaceId',
  path: '/myworkspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyworkspacesWorkspaceIdIndexRoute =
  MyworkspacesWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MyworkspacesWorkspaceIdRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/myworkspaces/$workspaceId': typeof MyworkspacesWorkspaceIdRouteWithChildren
  '/myworkspaces/': typeof MyworkspacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/myworkspaces/$workspaceId/': typeof MyworkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/myworkspaces': typeof MyworkspacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/myworkspaces/$workspaceId': typeof MyworkspacesWorkspaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/myworkspaces/$workspaceId': typeof MyworkspacesWorkspaceIdRouteWithChildren
  '/myworkspaces/': typeof MyworkspacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/myworkspaces/$workspaceId/': typeof MyworkspacesWorkspaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/myworkspaces/$workspaceId'
    | '/myworkspaces/'
    | '/api/auth/$'
    | '/myworkspaces/$workspaceId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/myworkspaces' | '/api/auth/$' | '/myworkspaces/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/myworkspaces/$workspaceId'
    | '/myworkspaces/'
    | '/api/auth/$'
    | '/myworkspaces/$workspaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyworkspacesWorkspaceIdRoute: typeof MyworkspacesWorkspaceIdRouteWithChildren
  MyworkspacesIndexRoute: typeof MyworkspacesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myworkspaces/': {
      id: '/myworkspaces/'
      path: '/myworkspaces'
      fullPath: '/myworkspaces/'
      preLoaderRoute: typeof MyworkspacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myworkspaces/$workspaceId': {
      id: '/myworkspaces/$workspaceId'
      path: '/myworkspaces/$workspaceId'
      fullPath: '/myworkspaces/$workspaceId'
      preLoaderRoute: typeof MyworkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/myworkspaces/$workspaceId/': {
      id: '/myworkspaces/$workspaceId/'
      path: '/'
      fullPath: '/myworkspaces/$workspaceId/'
      preLoaderRoute: typeof MyworkspacesWorkspaceIdIndexRouteImport
      parentRoute: typeof MyworkspacesWorkspaceIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MyworkspacesWorkspaceIdRouteChildren {
  MyworkspacesWorkspaceIdIndexRoute: typeof MyworkspacesWorkspaceIdIndexRoute
}

const MyworkspacesWorkspaceIdRouteChildren: MyworkspacesWorkspaceIdRouteChildren =
  {
    MyworkspacesWorkspaceIdIndexRoute: MyworkspacesWorkspaceIdIndexRoute,
  }

const MyworkspacesWorkspaceIdRouteWithChildren =
  MyworkspacesWorkspaceIdRoute._addFileChildren(
    MyworkspacesWorkspaceIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyworkspacesWorkspaceIdRoute: MyworkspacesWorkspaceIdRouteWithChildren,
  MyworkspacesIndexRoute: MyworkspacesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
